image: node:13-alpine

before_script:
  - apk add yarn --no-cache

cache:
  paths:
    - node_modules/

build:
  stage: deploy
  script:
    - yarn install --prod
  artifacts:
    paths:
    - build
  only:
  - master
