image: node:13-alpine

before_script:
  - apk add yarn --no-cache
  - yarn install --prod

cache:
  paths:
    - node_modules/

build:
  stage: deploy
  script:
    - node dist/main/index.js
  artifacts:
    paths:
    - dist
  only:
  - master
