image: node:13-alpine

before_script:
  - yarn install

cache:
  paths:
    - node_modules/

build:
  stage: deploy
  script:
    - yarn install --prod
    - node dist/main/index.js
  artifacts:
    paths:
    - dist
  only:
  - master
