image: node:13-alpine
stages:
  - build
  - release # Versionamento
  - deploy

cache:
  untracked: false
  policy: pull-push

project-build:
  stage: build
  script:
    - cp .env.example .env
    - yarn install --freeze-lockfile --prefer-offline --cache-folder .yarn-cache/
    - yarn compile
  artifacts:
    paths:
      - dist/
      - package.json
      - yarn.lock
      - .env
  only:
  - master

release-project:
  stage: release
  script:
    # Versione o projeto
    # Build do docker 
    # Tagear a imagem
    # docker push repo
    - 

deploy:
  stage: deploy
