version: "3.7"
services: 
  back:
    image: node:lts-alpine
    container_name: backend
    working_dir: /home/app
    volumes:
      - .:/home/app
    ports: 
      - 9300:3000
    entrypoint: 'node dist/index.js'
    env_file: 
      - .env 
    depends_on: 
      - database
    links: 
      - database

  database:
    image: mongo
    container_name: restifycourse_db
    ports: 
      - 27017
    restart: always
    volumes:
      - mongodb:/data/db
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: K1WaMs04sbnNV6sb1ZE7RPTlOm7V4kG

volumes:
  mongodb:

networks:
  restify: