version: "3.7"
services: 
  back:
    image: node
    container_name: backend
    volumes:
      - ./:/home/node/app
    ports: 
      - "8080:8080"
    command: node
    environment: 
      - NODE_ENV=developement 
    depends_on: 
      - db

  db:
    image: mongo
    container_name: restifycourse_db
    ports: 
      - "27017:27017"
    restart: always
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: K1WaMs04sbnNV6sb1ZE7RPTlOm7V4kG 